version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Java / Gradle
  - package-ecosystem: "gradle"
    directory: "/src/adservice"
    schedule:
      interval: "weekly"

  # Node.js / npm
  - package-ecosystem: "npm"
    directory: "/src/currencyservice"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "protobufjs"
      - dependency-name: "uuid"
  - package-ecosystem: "npm"
    directory: "/src/paymentservice"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "protobufjs"
      - dependency-name: "uuid"

  # Python / pip
  - package-ecosystem: "pip"
    directory: "/src/shoppingassistantservice"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/src/loadgenerator"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/src/emailservice"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/src/recommendationservice"
    schedule:
      interval: "weekly"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/src/adservice"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/src/cartservice/src"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/src/checkoutservice"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/src/currencyservice"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/src/emailservice"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/src/frontend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/src/loadgenerator"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/src/paymentservice"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/src/productcatalogservice"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/src/recommendationservice"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/src/shippingservice"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/src/shoppingassistantservice"
    schedule:
      interval: "weekly"
