blank_issues_enabled: false
contact_links:
  - name: Report a security vulnerability
    url: https://g.co/vulnz
    about: For confirmed security vulnerabilities, please report via g.co/vulnz for responsible disclosure.
