[SERVICE]
    Flush         1
    Daemon        Off
    Log_Level     info

[INPUT]
    Name              tail
    Path              /var/log/app/*.log
    Parser            json
    Tag               app.logs
    Mem_Buf_Limit     10MB
    Skip_Long_Lines   On

[OUTPUT]
    Name              kafka
    Brokers           kafka:29092
    Topics            app_logs
    Timestamp_Key     event_time
    Retry_Limit       false
