name: "Node Service Tests"

on:
  pull_request:
    paths:
      - "src/currencyservice/**"
      - "src/paymentservice/**"
      - ".github/workflows/node-service-tests-ci.yaml"
  push:
    branches: ["main"]
    paths:
      - "src/currencyservice/**"
      - "src/paymentservice/**"
      - ".github/workflows/node-service-tests-ci.yaml"

jobs:
  node-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["currencyservice", "paymentservice"]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: src/${{ matrix.service }}/package-lock.json
      - name: Install
        working-directory: src/${{ matrix.service }}
        run: npm ci
      - name: Test
        working-directory: src/${{ matrix.service }}
        run: npm test
